name: Rust build&test arcrunner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        runner: [arc-runner-set]
    
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Install
      run: sudo apt update && sudo apt upgrade -y && sudo apt install -y git build-essential cmake curl pkg-config libssl-dev libclang-dev
    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: cargo build -vv
    - name: Run tests
      run: cargo test -vv