name: Rust build&test arcrunner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        runner: [arc-runner-set]
    
    runs-on: ${{ matrix.runner }}
    container: docker.io/rust:latest

    steps:
    - name: Setup | CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.24.0'
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: cargo build -vv
    - name: Run tests
      run: cargo test -vv